import os
from moviepy import VideoFileClip, concatenate_videoclips

# Configuration paths
human_video_path = "../../SaveClip.App_AQOEdDT0Y70E6PsLNh9LNyaxSkv8oZEd0JjefkDWn9pEHtgnZOSBhn7mLmf5_Jf-SZpL8FoBPiMtlHKA8Gh7wEohO6hLdtGmn905FmA.mp4"
app_video_dir = "videos"

# Find the webm file generated by playwright
app_video_path = None
for f in os.listdir(app_video_dir):
    if f.endswith(".webm"):
        app_video_path = os.path.join(app_video_dir, f)
        break

if not app_video_path:
    print("Error: No webm file found in videos/ directory.")
    exit(1)

try:
    print("Loading clips...")
    # Load the dummy human video and cut the first 2 seconds to simulate a question
    human_clip = VideoFileClip(human_video_path).subclipped(0, 2)
    
    # Resize human clip to match the app video width (390x844) to avoid concatenation errors
    human_clip = human_clip.resized(width=390)
    
    # Load the captured app simulator video
    app_clip = VideoFileClip(app_video_path)
    
    # Assure dimensions match exactly or pad them (simplified for POC)
    if human_clip.size != app_clip.size:
        print(f"Warning: Sizes differ. Human: {human_clip.size}, App: {app_clip.size}. Resizing app clip.")
        app_clip = app_clip.resized(human_clip.size)

    print("Concatenating clips (Ping-Pong effect)...")
    # Assemble: Human asking -> App responding
    final_clip = concatenate_videoclips([human_clip, app_clip], method="compose")

    output_path = "final_poc_video.mp4"
    print(f"Exporting to {output_path}...")
    final_clip.write_videofile(output_path, fps=24, codec="libx264", audio_codec="aac")
    
    print("Done! POC assembly successful.")
except Exception as e:
    print(f"An error occurred during montage: {e}")
